### ISSUE TITLE
Implement org.ehcache.integrations.shiro.EhcacheShiro#values by wrapping over the cache

### ISSUE THREAD

**Issue by ljacomet** [ehcache/ehcache-shiro#7]
Assuming we can make that return collection unmodifiable - which seems to be the case in current implementation of the ehcache 2.x module, it would be better to have a delegation model to the cache, thus making sure we do not have to materialise the whole value collection on heap.

**Comment by nenko-tabakov** [comment]
Merged - [Pull Request#11](https://github.com/ehcache/ehcache-shiro/pull/11)
